### ISSUE TITLE
Why scene_013、014、016、018 dont't have head annotations?

### ISSUE THREAD

**Issue by sandydf** [daizhirui/BEVNet#2]
Thanks for the interesting work! Could you tell me why these scenes don't have head annotations? And are these head annotations in image view?

**Comment by daizhirui** [comment]
Thank you for asking.
1. We don't have annotations for some scenes because the data annotation service doesn't finish them with the required quality. 
2. Yes, the annotation is done in image view.

**Comment by sandydf** [comment]
Got it, thanks.
