### ISSUE TITLE
Question about ROI

### ISSUE THREAD

**Issue by sandydf** [daizhirui/BEVNet#4]
Thanks for the excellent work!
I want to know how to get the ROI? And when do we start to use the ROI region?  After obtaining the IV features of the whole image, select an ROI and only transfom the IV features of this ROI  into BEV features?

**Comment by daizhirui** [comment]
Thanks for asking. The ROI is computed by https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/bevnet/bev_transform.py#L205-L219

The ROI is used for evaluation and visualization.

**Comment by sandydf** [comment]
Thanks for your reply!  I'd like to confirm again. Was the ROI not used at all in the process of generating the BEV map? Does ROI refer to which area in the input image the generated BEV map corresponds to?

**Comment by daizhirui** [comment]
Yes, the ROI is just used to mark the BEV area in the image.

**Comment by sandydf** [comment]
Thanks!
